# This is the deployment configuration for the payments-api application. It defines a single replica of the application, 
# which runs a stress test to simulate high memory usage. 
# The liveness probe checks if the stress process is running to ensure the application is healthy.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: polinux/stress:latest
          command: ["stress"]
          args: '[]'
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          livenessProbe:
            exec:
              command: ["pgrep", "stress"]
            initialDelaySeconds: 5
            periodSeconds: 15
